name: Pull Request

on: [pull_request]

jobs:
    install:
        name: Installing Packages
        build:
            runs-on: ubuntu-latest
            steps:
                #Passo 1
                - name: Checkout
                uses: actions/checkout@v4

                #Passo 2
                - name: Cache node_modules
                uses: actions/cache@v2
                with:
                    path: node_modules
                    key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

                #Passo 3
                - name: Install dependencies
                run: yarn install

    unusedexports:
        name: Find unused exports (dead code)
        build:
            runs-on: ubuntu-latest
            needs: install
            steps:
                #Passo #
                - name: Checkout
                uses: actions/checkout@v4

                #Passo 4
                - name: Restore node_modules
                uses: actions/cache@v2
                with:
                    path: node_modules
                    key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
                
                #Passo 5
                - name: Run ts-prone
                run: yarn ts-prune --errror

    testing:
        name: Run unit test
        build:
            runs-on: ubuntu-latest
            needs: unusedexports
            steps:
                #Passo #
                - name: Checkout
                uses: actions/checkout@v4

                #Passo #
                - name: Restore node_modules
                uses: actions/cache@v2
                with:
                    path: node_modules
                    key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
                
                #Passo 6
                - name: Run unit test
                run: yarn ts-prune --errror
  