name: appAngular

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
        # Passo 1
      - name: checkout
        uses: actions/checkout@v4

        # Passo 2
      - name: Cache node_modules
        uses: actions/cache@v2
        with:
            path: node_modules
            key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

        # Passo 3
      - name: Install dependencies
        run: yarn install

        # Passo 4
      - name: Run ts-prone
        run: yarn ts-prune --errror

        # Passo 5
      - name: Run unit test
        run: yarn ts-prune --errror

        # Passo 6
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
        